var urlprefix = "2dcraft/changelog/"

loadversion(urlprefix, "0.8.24");
loadversion(urlprefix, "0.8.23");
loadversion(urlprefix, "0.8.22");
loadversion(urlprefix, "0.8.21");
loadversion(urlprefix, "0.8.20");
loadversion(urlprefix, "0.8.19");
loadversion(urlprefix, "0.8.18");
loadversion(urlprefix, "0.8.17");
loadversion(urlprefix, "0.8.16");
loadversion(urlprefix, "0.8.15");
loadversion(urlprefix, "0.8.14");
loadversion(urlprefix, "0.8.13");
loadversion(urlprefix, "0.8.12");
loadversion(urlprefix, "0.8.11");
loadversion(urlprefix, "0.8.10");
loadversion(urlprefix, "0.8.9");
loadversion(urlprefix, "0.8.8");
loadversion(urlprefix, "0.8.7" );
loadversion(urlprefix, "0.8.6");
loadversion(urlprefix, "0.8.5");
loadversion(urlprefix, "0.8.4");
loadversion(urlprefix, "0.8.3");
loadversion(urlprefix, "0.8.2");
loadversion(urlprefix, "0.8.1");
loadversion(urlprefix, "0.8");
loadversion(urlprefix, "0.7.2");
loadversion(urlprefix, "0.7.1");
loadversion(urlprefix, "0.7");
loadversion(urlprefix, "0.6.4");
loadversion(urlprefix, "0.6.3");
loadversion(urlprefix, "0.6.2");
loadversion(urlprefix, "0.6.1");
loadversion(urlprefix, "0.6");
loadversion(urlprefix, "0.0.0.1_0.5.7");